version: '3.7'
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
