#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

"$SCRIPT_DIR"/run-sql "

CREATE TABLE IF NOT EXISTS scans (
  \"id\" serial primary key,
  \"scanned_at\" timestamp with time zone UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS device_names (
  \"mac\" varchar(32) primary key,
  \"device_name\" varchar(128)
);

CREATE TABLE IF NOT EXISTS scan_records (
  \"scan_id\" integer references scans,
  \"ip\" varchar(16) NOT NULL,
  \"mac\" varchar(32),
  \"hostname\" varchar(128),
  \"vendor\" varchar(128),
  \"srtt\" INT,
  \"rttvar\" INT,
  \"to\" INT,
  PRIMARY KEY (scan_id, ip)
);
"
